quarkus.devservices.enabled=false

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=app
quarkus.datasource.password=app

quarkus.datasource.jdbc.url=jdbc:postgresql://db:5432/app
quarkus.datasource.jdbc.max-size=16

quarkus.flyway.migrate-at-start=true

quarkus.mailer.auth-methods=DIGEST-MD5 CRAM-SHA256 CRAM-SHA1 CRAM-MD5 PLAIN LOGIN
quarkus.mailer.from=abiplaner.jsg@gmail.com
quarkus.mailer.host=smtp.gmail.com
quarkus.mailer.port=587
quarkus.mailer.start-tls=REQUIRED
quarkus.mailer.username=abiplaner.jsg@gmail.com
quarkus.mailer.password=stvl xygv nfys bwau

quarkus.mailer.mock=false


quarkus.http.cors=true
quarkus.http.cors.origins=https://abiplaner.hopto.org:3000
quarkus.http.cors.methods=GET,POST,OPTIONS
quarkus.http.cors.headers=Content-Type, Authorization
quarkus.http.cors.allow-credentials=true

quarkus.oidc.enabled=false