CREATE TABLE bestellung
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
    benutzer_id        TEXT    NOT NULL,
    benutzer_email     TEXT    NOT NULL,
    anzahl_essenskarte INTEGER NOT NULL,
    anzahl_abendkarte  INTEGER NOT NULL,
    bezahlt            BOOLEAN NOT NULL,
    email_versendet    BOOLEAN NOT NULL DEFAULT false,
    PRIMARY KEY (id)
);

CREATE INDEX bestellung_benutzer_id on bestellung (benutzer_id);